# Generated by Django 4.0.2 on 2022-02-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='productid',
        ),
    ]
