# Generated by Django 4.0.2 on 2022-02-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insert', '0002_remove_products_productid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='product',
        ),
    ]
